language: c

compiler:
  - gcc
  - clang

before-install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - cp -r ../conf . && mkdir log
  - ./bitzer -p . -t

notifications:
  email:
    - idealities@gmail.com
